export const LOGIN_USER_SUCCESS = 'login_user_success';
export const LOGIN_USER_FAIL= 'login_user_fail';
export const LOGIN_USER =' login_user';
export const EMPLOYEE_UPDATE = 'employee_update';
export const EMPLOYEE_CREATE = 'employee_create';
export const EMPLOYEE_FETCH_SUCCESS= 'employee_fetch_success';
export const EMPLOYEE_SAVE_SUCCESS = 'employee_save_success';

export const NAME_CHANGED='NAME_CHANGED';
export const ADDRESS_CHANGED='ADDRESS_CHANGED';
export const CONTACT_CHANGED='CONTACT_CHANGED';
export const CNIC_CHANGED='CNIC_CHANGED';
export const AGE_CHANGED='AGE_CHANGED';
export const CLASS_CHANGED='CLASS_CHANGED';
export const INSTITUTE_CHANGED='INSTITUTE_CHANGED';
export const SUBJECTS_CHANGED='SUBJECTS_CHANGED';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export  const PASSWORD_CHANGED ='PASSWORD_CHANGED';
export const CREATE_STUDENT = "CREATE_STUDENT";
export const SIGNUP_STUDENT="SIGNUP_STUDENT";
export const SIGNUP_STUDENT_SUCCESS="SIGNUP_STUDENT_SUCCESS";
export const SIGNUP_STUDENT_FAIL="SIGNUP_STUDENT_FAIL";
export const STUDENT_CREATE_SUCCESS="STUDENT_CREATE_SUCCESS";
export const STUDENT_CREATE_FAIL="STUDENT_CREATE_FAIL";
export const IMAGE_PICKED="IMAGE_PICKED";
export const STUDENT_FETCH_SUCCESS="STUDENT_FETCH_SUCCESS"
export const SELECTED_STUDENT_FETCH ="SELECTED_STUDENT_FETCH"
export const CHANGE_PROFILES="CHANGE_PROFILES"